apps/calendar/urls.py
from django.urls import path

from apps.calendar import views

app_name = "calendar"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:year>/<int:month>", views.index, name="index_by_year_month"),
    path("events/add-modal", views.event_add_modal, name="event_add_modal"),
    path("events/<int:pk>/edit-modal", views.event_edit_modal, name="event_edit_modal"),
    path("events/<int:pk>/delete-modal", views.event_delete_modal, name="event_delete_modal"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "todomvc/",
        include("apps.todomvc.urls", namespace="todomvc"),
        name="todomvc",
    ),
    path(
        "calendar/",
        include("apps.calendar.urls", namespace="calendar"),
        name="calendar",
    ),
    path(
        "__reload__/",
        include("django_browser_reload.urls"),
    ),
]

todomvc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("apps.todos.urls", namespace="todos"),
        name="todos",
    ),
    path(
        "__reload__/",
        include("django_browser_reload.urls"),
    ),
]

apps/calendar/models.py
from django.db import models


class Event(models.Model):
    name = models.CharField(max_length=255)
    start = models.DateTimeField()

apps/calendar/forms.py
from django import forms

from apps.calendar.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ("name", "start")

        widgets = {
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "My event"}
            ),
            "start": forms.DateTimeInput(attrs={"class": "form-control datepicker"}),
        }

apps/calendar/views.py
import calendar
import datetime

from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django_htmx.http import HttpResponseLocation

from apps.calendar.forms import EventForm
from apps.calendar.models import Event


class CalendarDay:
    def __init__(self, date, events):
        self.date: datetime.date = date
        self.events: list[Event] = events


def get_calendar_days_by_weeks(
    year, month, events: list[Event]
) -> list[list[CalendarDay]]:
    calendar_days = []

    cal = calendar.Calendar(calendar.MONDAY)
    for date in cal.itermonthdates(year=year, month=month):
        events_for_date = [event for event in events if event.start.date() == date]
        calendar_day = CalendarDay(date, events_for_date)
        calendar_days.append(calendar_day)

    return [calendar_days[i : i + 7] for i in range(0, len(calendar_days), 7)]


def index(request: HttpRequest, year=None, month=None) -> HttpResponse:
    if year is None or month is None:
        year = datetime.date.today().year
        month = datetime.date.today().month

    events = Event.objects.filter(start__year=year, start__month=month).order_by(
        "start"
    )
    next_month_date = datetime.date(year, month, 1) + datetime.timedelta(days=35)
    previous_month_date = datetime.date(year, month, 1) - datetime.timedelta(days=10)

    return render(
        request,
        "calendar/index.html",
        context={
            "calendar": calendar.Calendar(calendar.MONDAY),
            "today": datetime.date.today(),
            "weeks": get_calendar_days_by_weeks(year, month, events),
            "next_month_date": next_month_date.replace(day=1),
            "previous_month_date": previous_month_date.replace(day=1),
            "year": year,
            "month": month,
        },
    )


@require_http_methods(["GET", "POST"])
def event_add_modal(request) -> HttpResponse:
    given_date = request.GET.get("date", datetime.date.today().strftime("%Y-%m-%d"))
    form = EventForm(request.POST or None, initial={"start": given_date})
    if request.method == "POST" and form.is_valid():
        form.save()
        return HttpResponseLocation(request.htmx.current_url)
    return render(
        request,
        "calendar/event_add_modal.html",
        context={"form": form, "form_url": reverse("calendar:event_add_modal")},
    )


@require_http_methods(["GET", "POST"])
def event_edit_modal(request, pk: int) -> HttpResponse:
    form = EventForm(request.POST or None, instance=get_object_or_404(Event, pk=pk))
    if request.method == "POST" and form.is_valid():
        form.save()
        return HttpResponseLocation(request.htmx.current_url)
    return render(
        request,
        "calendar/event_add_modal.html",
        context={
            "form": form,
            "form_url": reverse("calendar:event_edit_modal", kwargs={"pk": pk}),
        },
    )


@require_http_methods(["GET", "DELETE"])
def event_delete_modal(request, pk: int) -> HttpResponse:
    event = get_object_or_404(Event, pk=pk)
    if request.method == "DELETE":
        event.delete()
        return HttpResponseLocation(request.htmx.current_url)

    return render(
        request, "calendar/event_delete_confirm_modal.html", context={"event": event}
    )

apps/calendar/templates/calendar/base.html
{% load static %}
{% load django_browser_reload %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Django with Htmx - Calendar</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Boostrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  <!-- htmx -->
  <script src="{% static "core/js/htmx.1.9.10.js" %}" defer></script>
  <script src="//unpkg.com/alpinejs" defer></script>

  <!-- Bootstrap js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
          crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

  <style>
    [x-cloak] {
      display: none !important;
    }

    .htmx-hidden-when-request { display: inline-block; }
    .htmx-displayed-when-request { display: none; }
    .htmx-request .htmx-displayed-when-request { display: inline-block }
    .htmx-request .htmx-hidden-when-request { display: none; }

  </style>

</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' x-data="{}">
{% block content %}
{% endblock %}

{% django_browser_reload_script %}
</body>
</html>

apps/calendar/templates/calendar/event_add_modal.html
<div
  class="modal-dialog"
  hx-on:htmx:load="flatpickr('.datepicker', {enableTime: true, dateFormat: 'Y-m-d H:i', time_24hr: true})"
  x-data="{
    isSaving: false,
    isDeleting: false
  }"
>
  <div class="modal-content">

    <div class="modal-header">
      <h5 class="modal-title">
        {% if form.instance.pk %}
          Edit : {{ form.instance.name }}
        {% else %}
          New event
        {% endif %}
      </h5>
      <button class="btn-close" data-bs-dismiss="modal" aria-label='Close' type="button"></button>
    </div>

    <div class="modal-body">
      <form
        id="event-add-modal-form"
        hx-post="{{ form_url }}"
        hx-target="closest .modal-dialog"
        hx-swap="outerHTML"
        @htmx:before-request="isSaving=true"
      >{% csrf_token %}
        {{ form }}
      </form>
    </div>

    <div class="modal-footer">
      {% if form.instance.pk %}
        <button
          hx-get="{% url "calendar:event_delete_modal" pk=form.instance.pk %}"
          hx-target="closest .modal-dialog"
          hx-swap="outerHTML"
          @htmx:before-request="isDeleting=true"
          class="btn btn-warning"
        >
          <span x-show="!isDeleting">Delete</span>
          <span x-show="isDeleting" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
        </button>
      {% endif %}
      <button class="btn btn-secondary" data-bs-dismiss="modal" type="button">Close</button>
      <button
        class="btn btn-primary"
        type="submit"
        form="event-add-modal-form"
      >
          <span x-show="!isSaving">Save changes</span>
          <span x-show="isSaving" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      </button>
    </div>
  </div>
</div>

apps/calendar/templates/calendar/event_delete_confirm_modal.html
<div
  class="modal-dialog"
  x-data="{isDeleting: false}"
>
  <div class="modal-content">

    <div class="modal-header">
      <h5 class="modal-title">Suppression de : {{ event.name }}</h5>
      <button class="btn-close" data-bs-dismiss="modal" aria-label='Close' type="button"></button>
    </div>

    <div class="modal-body">
      Êtes-vous sur de vouloir supprimer l'évènement de votre calendier du {{ event.start|date }}{{ event.start| time }} ?
    </div>

    <div class="modal-footer">
      <button class="btn btn-secondary" data-bs-dismiss="modal" type="button">Close</button>
      <button
        hx-delete="{% url "calendar:event_delete_modal" pk=event.pk %}"
        @htmx:before-request="isDeleting=true"
        class="btn btn-warning"
      >
          <span x-show="!isDeleting">Delete permanently</span>
          <span x-show="isDeleting" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      </button>
    </div>

  </div>
</div>

apps/calendar/templates/calendar/index.html
{% extends "calendar/base.html" %}
{% load calendar_tags %}

{% load static %}

{% block content %}
  <div class="container">
    <div class="card mt-3">
      <div class="card-header">
        <h1>Calendar - {{ month|month_name }}</h1>
      </div>
      <div id="calendar" class="card-body">

        <!-- Bouton pour naviguer dans le calendrier -->
        <div class="d-flex justify-content-between align-items-center">
          <h2 id="current-month">{{ current_month }}</h2>

          <div class="text-success" hidden='' data-activity-indicator=''>
            <div class="spinner-border spinner-border-sm"></div>
            <span>Loading ...</span>
          </div>

          <div>
            <button
              class="btn btn-secondary me-2 btn-sm"
              type="button"
              hx-get="{% url "calendar:index" %}"
              hx-target="body"
              data-bs-toggle="tooltip"
              data-bs-placement="top"
              title="Today"
            >
              <span class="htmx-hidden-when-request">Today</span>
              <span class="spinner-border spinner-border-sm htmx-displayed-when-request" role="status" aria-hidden="true"></span>
            </button>

            <button
              hx-get="{% url "calendar:index_by_year_month" year=previous_month_date.year month=previous_month_date.month %}"
              hx-target="body"
              hx-push-url="true"
              data-bs-toggle="tooltip"
              data-bs-placement="top"
              title="Previous Month"
              type="button"
              class="btn btn-secondary ms-2 btn-sm"
            >
              <img class="htmx-hidden-when-request"  src="{% static "calendar/icons/chevron-left.svg" %}" alt="Previous">
              <span class="spinner-border spinner-border-sm htmx-displayed-when-request" role="status" aria-hidden="true"></span>
            </button>

            <button
              hx-get="{% url "calendar:index_by_year_month" year=next_month_date.year month=next_month_date.month %}"
              hx-target="body"
              hx-push-url="true"
              data-bs-toggle="tooltip"
              data-bs-placement="top"
              title="Next Month"
              type="button"
              class="btn btn-secondary me-2 btn-sm"
            >
              <img class="htmx-hidden-when-request" src="{% static "calendar/icons/chevron-right.svg" %}" alt="Next">
              <span class="spinner-border spinner-border-sm htmx-displayed-when-request" role="status" aria-hidden="true"></span>
            </button>

          </div>

        </div>


        <!-- Tableau qui représente le calendrier -->
        <table class="table table-bordered mt-2">
          <thead class="table-dark">
          {% for day_number in calendar.iterweekdays %}
            <th style="width:14.2%"> {{ day_number|day_name }}</th>
          {% endfor %}
          </thead>

          <tbody>
          {% for week in weeks %}
            <tr class="table-light">
              {% for day in week %}
                <td
                  hx-get="{% url "calendar:event_add_modal" %}?date={{ day.date.year }}-{{ day.date.month }}-{{ day.date.day }}"
                  hx-target="#modals-here"
                  hx-trigger="click"
                  data-bs-toggle="modal"
                  data-bs-target="#modals-here"
                  class="{% if day.date == today %}table-info{% endif %}"
                  role="button"
                >
                  <span>{% if day.date.month == month %}{{ day.date.day }}{% endif %}</span>
                  <div
                    class="mt-2"
                    style="height:65px;"
                  >
                    {% for e in day.events %}
                      <div
                        hx-get="{% url "calendar:event_edit_modal" pk=e.pk %}"
                        hx-target="#modals-here"
                        hx-trigger="click consume"
                        data-bs-toggle="modal"
                        data-bs-target="#modals-here"
                        class="badge text-bg-info text-start w-100 pe-0"
                        role="button"
                      >
                        {{ e.start.hour }}:{{ e.start.minute }} - {{ e.name }}
                      </div>
                    {% endfor %}
                  </div>
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
          </tbody>
        </table>

        <!-- Modal -->
        <div
          id="modals-here"
          class="modal fade"
          tabindex="-1"
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
          @htmx:before-request.window="
            if ($event.detail.target === $el){
              $el.innerHTML = document.querySelector('#template-inner-modal').innerHTML
            }
          "
        >
          <div class="modal-dialog" role="document"></div>
        </div>

        <!-- for template -->
        <template id="template-inner-modal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Loading ...</h5>
                <button class="btn-close" data-bs-dismiss="modal" aria-label='Close' type="button"></button>
              </div>
              <div class="modal-body m-auto p-5">
                <div class="spinner-border" role="status"></div>
              </div>
            </div>
          </div>
        </template>

      </div>
    </div>
  </div>
{% endblock %}