project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "todomvc/",
        include("apps.todomvc.urls", namespace="todomvc"),
        name="todomvc",
    ),
    path(
        "calendar/",
        include("apps.calendar.urls", namespace="calendar"),
        name="calendar",
    ),
    path(
        "__reload__/",
        include("django_browser_reload.urls"),
    ),
]

todomvc/core/urls.py
from django.urls import path, include

from todomvc.core.views import (
    TodoListView,
    TodoActiveListView,
    TodoCompletedListView,
    TodoToggleView,
    TodoToggleAllView,
    TodoClearCompletedView,
    TodoDeleteView,
    TodoCreateView,
    TodoUpdateView,
    TodoItemPartialView,
)

app_name = "todo"

urlpatterns = [
    path(
        "list/",
        include(
            (
                [
                    path("", TodoListView.as_view(), name="all"),
                    path("active", TodoActiveListView.as_view(), name="active"),
                    path("completed", TodoCompletedListView.as_view(), name="completed"),
                    path("toggle-all", TodoToggleAllView.as_view(), name="toggle-all"),
                    path("partial/item/<int:pk>", TodoItemPartialView.as_view(), name="item-partial"),
                    path("partial/item/<int:pk>/edit", TodoUpdateView.as_view(), name="item-edit-partial"),
                    path("clear-completed", TodoClearCompletedView.as_view(), name="clear-completed"),
                ],
                "list",
            )
        ),
    ),
    path("<int:pk>/toggle", TodoToggleView.as_view(), name="toggle"),
    path("<int:pk>/delete", TodoDeleteView.as_view(), name="delete-view"),
    path("create", TodoCreateView.as_view(), name="create"),
]

todomvc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("apps.todos.urls", namespace="todos"),
        name="todos",
    ),
    path(
        "__reload__/",
        include("django_browser_reload.urls"),
    ),
]

todomvc/core/models.py
from django.db import models


class TodoQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_done=False)

    def completed(self):
        return self.filter(is_done=True)

    def from_session(self, session_uuid):
        return self.filter(session_uuid=session_uuid)


class TodoManager(models.Manager.from_queryset(TodoQuerySet)):
    def toggle_all(self, session_uuid):
        qs = self.model.objects.from_session(session_uuid)
        if qs.filter(is_done=False).count() == 0:
            qs.update(is_done=False)
        else:
            qs.update(is_done=True)


class Todo(models.Model):
    title = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)
    session_uuid = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    objects = TodoManager()

todomvc/core/views.py
import uuid

from django.http import HttpResponse, Http404
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.detail import SingleObjectMixin, DetailView

from todomvc.core.form import TodoForm, TodoUpdateForm
from todomvc.core.models import Todo


def get_session_key(request):
    """Get or create a todolist for the current session."""
    session_uuid = request.session.get("todo_uuid", str(uuid.uuid4()))
    request.session["todo_uuid"] = session_uuid
    return session_uuid


def htmx_redirect(url):
    return HttpResponse(
        content="",
        status=204,
        headers={"HX-Location": url},
    )


class TodoSessionMixin:
    def get_session_todo_queryset(self):
        return Todo.objects.filter(session_uuid=get_session_key(self.request))

    def get_queryset(self):
        return self.get_session_todo_queryset().order_by("-created_at")


class TodoListView(TodoSessionMixin, ListView):
    extra_context = {"menu": "all"}

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx["number_todo_active"] = self.get_queryset().filter(is_done=False).count()
        ctx["number_todo_completed"] = self.get_queryset().filter(is_done=True).count()
        ctx["number_todo_total"] = ctx["number_todo_active"] + ctx["number_todo_completed"]
        ctx["number_todo"] = len(self.object_list)
        ctx["form"] = TodoForm()
        return ctx


class TodoActiveListView(TodoListView):
    extra_context = {"menu": "active"}

    def get_queryset(self):
        return super().get_queryset().filter(is_done=False)


class TodoCompletedListView(TodoListView):
    extra_context = {"menu": "completed"}

    def get_queryset(self):
        return super().get_queryset().filter(is_done=True)


class TodoToggleView(TodoSessionMixin, SingleObjectMixin, View):
    def post(self, request, *args, **kwargs):
        if not request.htmx:
            raise Http404()

        todo = self.get_object()
        todo.is_done = not todo.is_done
        todo.save()
        return htmx_redirect(request.htmx.current_url)


class TodoToggleAllView(TodoSessionMixin, View):
    def post(self, request, *args, **kwargs):
        if not request.htmx:
            raise Http404()

        qs = self.get_queryset()

        if qs.filter(is_done=False).count() == 0:
            qs.update(is_done=False)
        else:
            qs.update(is_done=True)

        return htmx_redirect(request.htmx.current_url)


class TodoItemPartialView(TodoSessionMixin, DetailView):
    template_name = "core/todo_item.html"


class TodoDeleteView(TodoSessionMixin, SingleObjectMixin, View):
    def delete(self, request, *args, **kwargs):
        todo = self.get_object()
        todo.delete()
        return htmx_redirect(request.htmx.current_url)


class TodoClearCompletedView(TodoSessionMixin, View):
    def delete(self, request, *args, **kwargs):
        if not request.htmx:
            raise Http404()

        self.get_queryset().filter(is_done=True).delete()

        return htmx_redirect(request.htmx.current_url)


class TodoCreateView(CreateView):
    form_class = TodoForm

    def get(self, request, *args, **kwargs):
        """Create view is only used for saving data, not for displaying form"""
        raise Http404()

    def form_valid(self, form):
        form.instance.session_uuid = get_session_key(self.request)
        form.save()
        return htmx_redirect(self.request.htmx.current_url)

    def form_invalid(self, form):
        # Dont handle form error for now.
        return htmx_redirect(self.request.htmx.current_url)


class TodoUpdateView(TodoSessionMixin, UpdateView):
    form_class = TodoUpdateForm
    template_name = "core/todo_item_edit.html"

    def form_valid(self, form):
        form.save()
        return htmx_redirect(self.request.htmx.current_url)

    def form_invalid(self, form):
        # Dont handle form error for now.
        return htmx_redirect(self.request.htmx.current_url)

todomvc/core/templates/core/base.html
{% load static %}
{% load django_browser_reload %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Django with Htmx</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- todomvc css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/todomvc-app-css@2.4.2/index.css">

  <!-- htmx -->
  <script src="{% static "core/js/htmx.1.8.0.min.js" %}" defer></script>
  <script src="{% static "core/js/_hyperscript.0.9.7.min.js" %}"></script>


</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
<section class="todoapp">
  {% block content %}
  {% endblock %}
</section>
{% django_browser_reload_script %}
</body>
</html>

todomvc/core/templates/core/todo_item.html
<li {% if object.is_done %}class="completed"{% endif %}>
  <div class="view">
    <input
      type="checkbox"
      {% if object.is_done %}checked{% endif %}
      hx-post="{% url "todo:toggle" pk=object.pk %}"
      class="toggle"
    >
    <label
      hx-get="{% url "todo:list:item-edit-partial" pk=object.pk %}"
      hx-trigger="dblclick"
      hx-target="closest li"
      hx-swap="outerHTML"
    >
      {{ object.title }}
    </label>
    <button
      hx-delete="{% url "todo:delete-view" pk=object.pk %}"
      class="destroy"
    >
    </button>
  </div>
</li>

todomvc/core/templates/core/todo_item_edit.html
<li
  hx-trigger="closeEditing"
  hx-get="{% url "todo:list:item-partial" pk=object.pk %}"
  hx-swap="outerHTML"
  class="editing"
  _="on click from elsewhere send closeEditing to me"
>
  <form
    action="{% url "todo:list:item-edit-partial" pk=object.pk %}"
    method="post"
    hx-boost="true"
  >
    {{ form.title }}
  </form>
</li>

todomvc/core/templates/core/todo_list.html
{% extends "core/base.html" %}

{% block content %}
  <header class="header">
    <h1>todos</h1>
    <form action="{% url "todo:create" %}" method="post" hx-boost="true">
      {{ form }}
    </form>
  </header>
  {% if number_todo_total %}
    <section class="main">
      <input
        id="toggle-all"
        {% if number_todo_active == 0 %}checked{% endif %}
        type="checkbox"
        hx-post="{% url "todo:list:toggle-all" %}"
        class="toggle-all"
      >
      <label for="toggle-all">Mark all as complete</label>
      <ul class="todo-list">
        {% for object in object_list %}
          {% include "core/todo_item.html" with object=object %}
        {% endfor %}
      </ul>
    </section>
    <footer class="footer">
      <span class="todo-count"><strong>{{ number_todo_active }}</strong> item left</span>
      <ul class="filters">
        <li>
          <a
            href="{% url "todo:list:all" %}"
            hx-boost="true"
            {% if menu == "all" %}class="selected"{% endif %}
          >
            All
          </a>
        </li>
        <li>
          <a
            href="{% url "todo:list:active" %}"
            hx-boost="true"
            {% if menu == "active" %}class="selected"{% endif %}
          >
            Active
          </a>
        </li>
        <li>
          <a
            href="{% url "todo:list:completed" %}"
            hx-boost="true"
            {% if menu == "completed" %}class="selected"{% endif %}
          >
            Completed
          </a>
        </li>
      </ul>
      {% if number_todo_completed %}
        <button
          hx-delete="{% url "todo:list:clear-completed" %}"
          class="clear-completed"
        >
          Clear completed
        </button>
      {% endif %}
    </footer>
  {% endif %}
{% endblock %}