apps/todos/urls.py
from django.urls import path

from . import views

app_name = "todos"

urlpatterns = [
    path("", views.todo_list, name="todo_list"),
    path("list/<str:filter_by>", views.todo_list, name="todo_list_with_params"),
    path("toggle/<int:pk>", views.todo_toggle, name="todo_toggle"),
    path("toggle-all", views.todo_toggle_all, name="todo_toggle_all"),
    path("partial-item/<int:pk>", views.todo_partial_item, name="todo_partial_item"),
    path("create", views.todo_create, name="todo_create"),
    path("edit/<int:pk>", views.todo_edit, name="todo_edit"),
    path("delete/<int:pk>", views.todo_delete, name="todo_delete"),
    path("clear-completed", views.todo_clear_completed, name="todo_clear_completed"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "todomvc/",
        include("apps.todomvc.urls", namespace="todomvc"),
        name="todomvc",
    ),
    path(
        "calendar/",
        include("apps.calendar.urls", namespace="calendar"),
        name="calendar",
    ),
    path(
        "__reload__/",
        include("django_browser_reload.urls"),
    ),
]

todomvc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("apps.todos.urls", namespace="todos"),
        name="todos",
    ),
    path(
        "__reload__/",
        include("django_browser_reload.urls"),
    ),
]

apps/todos/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from apps.todos.form import TodoForm
from apps.todos.models import Todo
from apps.todos.utils import get_session_key, htmx_redirect

from .shortcuts import get_todo_queryset_from_session


@require_http_methods(["GET"])
def todo_list(request, filter_by="all"):
    if filter_by not in ["active", "completed", "all"]:
        raise Http404()

    qs = get_todo_queryset_from_session(request).order_by("-created_at")

    todos = qs.all().by_status(filter_by)

    number_todo_active = qs.active().count()
    number_todo_completed = qs.completed().count()
    number_todo_total = number_todo_completed + number_todo_active

    return render(request, "todos/todo_list.html", context={
        "todos": todos,
        "number_todo_total": number_todo_total,
        "number_todo_active": number_todo_active,
        "number_todo_completed": number_todo_completed,
        "form": TodoForm()
    })


@require_http_methods(["POST"])
def todo_toggle(request, pk: int):
    todo = get_todo_queryset_from_session(request).get(pk=pk)
    todo.is_done = not todo.is_done
    todo.save()
    return htmx_redirect(request.htmx.current_url)


@require_http_methods(["POST"])
def todo_toggle_all(request):
    Todo.objects.toggle_all(get_session_key(request))
    return htmx_redirect(request.htmx.current_url)


@require_http_methods(["GET"])
def todo_partial_item(request, pk: int):
    todo = Todo.objects.from_session(get_session_key(request)).get(pk=pk)
    return render(request, "todos/todo_item.html", context=locals())


@require_http_methods(["POST"])
def todo_create(request):
    form = TodoForm(request.POST)
    if form.is_valid():
        form.save(session_uuid=request.todo_session_uuid)
    return htmx_redirect(request.htmx.current_url)


@require_http_methods(["GET", "POST"])
def todo_edit(request, pk: int):
    todo = get_object_or_404(Todo, session_uuid=request.todo_session_uuid, pk=pk)
    form = TodoForm(instance=todo, data=request.POST or None)
    if request.method == "POST" and form.is_valid():
        form.save(session_uuid=request.todo_session_uuid)
        return htmx_redirect(request.htmx.current_url)
    return render(request, "todos/todo_item_edit.html", context=locals())


@require_http_methods(["DELETE"])
def todo_delete(request, pk: int):
    get_object_or_404(Todo, session_uuid=request.todo_session_uuid, pk=pk).delete()
    return htmx_redirect(request.htmx.current_url)


@require_http_methods(["DELETE"])
def todo_clear_completed(request):
    Todo.objects.from_session(request.todo_session_uuid).completed().delete()
    return htmx_redirect(request.htmx.current_url)

apps/todos/templates/todos/todo_item.html
<li {% if todo.is_done %}class="completed"{% endif %}>
  <div class="view">
    <input
      type="checkbox"
      {% if todo.is_done %}checked{% endif %}
      hx-post="{% url "todos:todo_toggle" pk=todo.pk %}"
      class="toggle"
    >
    <label
      hx-get="{% url "todos:todo_edit" pk=todo.pk %}"
      hx-trigger="dblclick"
      hx-target="closest li"
      hx-swap="outerHTML"
    >
      {{ todo.title }}
    </label>
    <button
      hx-delete="{% url "todos:todo_delete" pk=todo.pk %}"
      class="destroy"
    >
    </button>
  </div>
</li>

apps/todos/templates/todos/todo_item_edit.html
<li
  hx-trigger="closeEditing"
  hx-get="{% url "todos:todo_partial_item" pk=todo.pk %}"
  hx-swap="outerHTML"
  class="editing"
  _="on click from elsewhere send closeEditing to me"
>
  <form
    action="{% url "todos:todo_edit" pk=todo.pk %}"
    method="post"
    hx-boost="true"
  >
    {{ form.title }}
  </form>
</li>

apps/todos/templates/todos/todo_list.html
{% extends "todos/base.html" %}

{% block content %}
  <header class="header">
    <h1>todos</h1>
    <form action="{% url "todos:todo_create" %}" method="post" hx-boost="true">
      {{ form }}
    </form>
  </header>
  {% if number_todo_total > 0 %}
    <section class="main">
      <input
        id="toggle-all"
        {% if number_todo_active == 0 %}checked{% endif %}
        type="checkbox"
        hx-post="{% url "todos:todo_toggle_all" %}"
        class="toggle-all"
      >
      <label for="toggle-all">Mark all as complete</label>
      <ul class="todo-list">
        {% for todo in todos %}
          {% include "todos/todo_item.html" with object=object %}
        {% endfor %}
      </ul>
    </section>
    <footer class="footer">
      <span class="todo-count"><strong>{{ number_todo_active }}</strong> item left</span>
      <ul class="filters">
        <li>
          <a
            href="{% url "todos:todo_list" %}"
            hx-boost="true"
            {% if menu == "all" %}class="selected"{% endif %}
          >
            All
          </a>
        </li>
        <li>
          <a
            href="{% url "todos:todo_list_with_params" filter_by="active" %}"
            hx-boost="true"
            {% if menu == "active" %}class="selected"{% endif %}
          >
            Active
          </a>
        </li>
        <li>
          <a
            href="{% url "todos:todo_list_with_params" filter_by="completed"  %}"
            hx-boost="true"
            {% if menu == "completed" %}class="selected"{% endif %}
          >
            Completed
          </a>
        </li>
      </ul>
      {% if number_todo_completed %}
        <button
          hx-delete="{% url "todos:todo_clear_completed" %}"
          class="clear-completed"
        >
          Clear completed
        </button>
      {% endif %}
    </footer>
  {% endif %}
{% endblock %}